export const wordList = [
    { foreign: "אנתרקס", hebrew: "גחלת" },
    { foreign: "אס-אם-אס", hebrew: "מסרון" },
    { foreign: "אסיסטנט", hebrew: "סייע" },
    { foreign: "אספירציה", hebrew: "שאיפה" },
    { foreign: "אספקט", hebrew: "הבט" },
    { foreign: "אסקלציה", hebrew: "הסלמה" },
    { foreign: "אסקפיזם", hebrew: "בורחנות" },
    { foreign: "אסתמה", hebrew: "קצרת" },
    { foreign: "אפטר", hebrew: "חופשון" },
    { foreign: "אפידמיה", hebrew: "מגפה" },
    { foreign: "אפיליפסיה", hebrew: "כפיון" },
    { foreign: "אפליקציה", hebrew: "יישומון" },
    { foreign: "אפנדיציט", hebrew: "תוספתן" },
    { foreign: "אפריטיף", hebrew: "אקדם" },
    { foreign: "אפתיה", hebrew: "אידשון" },
    { foreign: "אקוודוקט", hebrew: "אמת מים" },
    { foreign: "אקוויפר", hebrew: "אקווה" },
    { foreign: "אקווילייזר", hebrew: "שוויין" },
    { foreign: "אקונומי", hebrew: "כלכלי" },
    { foreign: "אקורד", hebrew: "תצליל" },
    { foreign: "אקורדיון", hebrew: "מפוחון" },
    { foreign: "אקזיט", hebrew: "הנפק" },
    { foreign: "אקזיסטציאלי", hebrew: "קיומי" },
    { foreign: "אקזמה", hebrew: "גרב" },
    { foreign: "אקטיבי", hebrew: "פעיל" },
    { foreign: "אקטיביזם", hebrew: "פעילנות" },
    { foreign: "אקנה", hebrew: "חטטת" },
    { foreign: "אקספוננציאלי", hebrew: "מעריכי" },
    { foreign: "אקספורט", hebrew: "יצוא" },
    { foreign: "אקצנט", hebrew: "מבטא" },
    { foreign: "אקרובט", hebrew: "לוליין" },
    { foreign: "אירובי", hebrew: "אווירני" },
    { foreign: "ארומה", hebrew: "בשומת" },
    { foreign: "ארטישוק", hebrew: "קנרס" },
    { foreign: "אתי", hebrew: "מוסרי" },
    { foreign: "באג", hebrew: "תקל" },
    { foreign: "באולינג", hebrew: "כדורת" },
    { foreign: "באז", hebrew: "רחשת" },
    { foreign: "באגאז'", hebrew: "תא מטען" },
    { foreign: "בדמינטון", hebrew: "נוצית" },
    { foreign: "בוטקה", hebrew: "שומרה" },
    { foreign: "בולדוזר", hebrew: "דחפור" },
    { foreign: "בולימיה", hebrew: "זללת" },
    { foreign: "בונקר", hebrew: "מבצור" },
    { foreign: "בופה", hebrew: "מזנון" },
    { foreign: "בורגול", hebrew: "ריפות" },
    { foreign: "בורי", hebrew: "קיפון" },
    { foreign: "בורשט", hebrew: "חמיצה" },
    { foreign: "בזיליקום", hebrew: "ריחן" },
    { foreign: "בטרייה", hebrew: "סוללה" },
    { foreign: "ביהביוריזם", hebrew: "התנהגותנות" },
    { foreign: "ביזנס", hebrew: "עסק" },
    { foreign: "בייבי גרו", hebrew: "מגמשת" },
    { foreign: "בייביסיטר", hebrew: "שמרטף" },
    { foreign: "בייגל", hebrew: "כעך" },
    { foreign: "בייסבול", hebrew: "כדור בסיס" },
    { foreign: "בילט אין", hebrew: "מובנה" },
    { foreign: "בילטרלי", hebrew: "דו צדדי" },
    { foreign: "ביס", hebrew: "נגיסה" },
    { foreign: "ביסקויט", hebrew: "מרקוע" },
    { foreign: "רולדה", hebrew: "גלילה" },
    { foreign: "סטייק", hebrew: "אומצה" },
    { foreign: "צ'יפס", hebrew: "טוגנים" },
    { foreign: "אאוטלט", hebrew: "חנות עודפים" },
    { foreign: "אאוטסורסינג", hebrew: "מיקור חוץ" },
    { foreign: "אאוטפוט", hebrew: "פלט" },
    { foreign: "אבסולוטי", hebrew: "מוחלט" },
    { foreign: "אבסטרקט", hebrew: "תקציר" },
    { foreign: "אבסטרקטי", hebrew: "מופשט" },
    { foreign: "אג'נדה", hebrew: "סדר יום" },
    { foreign: "אגואיזם", hebrew: "אנוכיות" },
    { foreign: "אגואיסט", hebrew: "אנוכי" },
    { foreign: "אגזוז", hebrew: "צינור פליטה" },
    { foreign: "אגרסיבי", hebrew: "תוקפני" },
    { foreign: "אדמינסטרטיבי", hebrew: "מנהלי" },
    { foreign: "אדפטציה", hebrew: "הסתגלות" },
    { foreign: "אובלי", hebrew: "סגלגל" },
    { foreign: "אובססיבי", hebrew: "טירדוני" },
    { foreign: "אובססיה", hebrew: "טירדון" },
    { foreign: "אוברדרפט", hebrew: "משיכת יתר" },
    { foreign: "אודיו", hebrew: "שמע" },
    { foreign: "אודישן", hebrew: "מבחן במה" },
    { foreign: "אווטר", hebrew: "יצגן" },
    { foreign: "אוטונומיה", hebrew: "ממשל עצמי" },
    { foreign: "אוטוסטרדה", hebrew: "דרך מהירה" },
    { foreign: "אולטרה סגול", hebrew: "על סגול" },
    { foreign: "אוליגרכיה", hebrew: "שלטון קומץ" },
    { foreign: "אומלט", hebrew: "חביתה" },
    { foreign: "אונומטופאה", hebrew: "תצליל" },
    { foreign: "אונליין", hebrew: "מקוון" },
    { foreign: "אוסמוזה", hebrew: "פעפוע" },
    { foreign: "אופוזיציה", hebrew: "נגדה" },
    { foreign: "אופורטוניזם", hebrew: "הזדמננות" },
    { foreign: "אופטימום", hebrew: "מיטב" },
    { foreign: "אופטימיזציה", hebrew: "מיטוב" },
    { foreign: "אופטימלי", hebrew: "מיטבי" },
    { foreign: "אופנסיבה", hebrew: "מתקפה" },
    { foreign: "אופסייד", hebrew: "נבדל" },
    { foreign: "אוקטגון", hebrew: "מתומן" },
    { foreign: "אוקסימורון", hebrew: "ניב ניגודים" },
    { foreign: "אורבני", hebrew: "עירוני" },
    { foreign: "אורגנו", hebrew: "אזובית" },
    { foreign: "אורגניזם", hebrew: "יצור" },
    { foreign: "אטימולוגיה", hebrew: "גיזרון" },
    { foreign: "אטצ'מנט", hebrew: "צרופה" },
    { foreign: "אטרקטיבי", hebrew: "מושך" },
    { foreign: "אידיום", hebrew: "ניב" },
    { foreign: "איי קיו", hebrew: "מנת משכל" },
    { foreign: "אייטם", hebrew: "פריט" },
    { foreign: "אילוזיה", hebrew: "אשליה" },
    { foreign: "אימג'", hebrew: "תמונה" },
    { foreign: "אימוג'י", hebrew: "סמלון" },
    { foreign: "אימיגרציה", hebrew: "הגירה" },
    { foreign: "אימייל", hebrew: "דואר אלקטרוני" },
    { foreign: "אימפולסיבי", hebrew: "פרצני" },
    { foreign: "אימפורט", hebrew: "יבוא" },
    { foreign: "אימפטיגו", hebrew: "גלדת" },
    { foreign: "אימפרוביזציה", hebrew: "אלתור" },
    { foreign: "אינג'יניר", hebrew: "מהנדס" },
    { foreign: "אינדיפרנטי", hebrew: "אדיש" },
    { foreign: "אינדקס", hebrew: "מדד" },
    { foreign: "אינטגריטי", hebrew: "יושרה" },
    { foreign: "אינטונציה", hebrew: "הנגנה" },
    { foreign: "אינטנסיבי", hebrew: "עצים" },
    { foreign: "אינטראקטיבי", hebrew: "הידודי" },
    { foreign: "אינטרדיסציפליני", hebrew: "בין תחומי" },
    { foreign: "אינטרנט", hebrew: "מרשתת" },
    { foreign: "אינטרנציונלי", hebrew: "בין לאומי" },
    { foreign: "אינסטלטור", hebrew: "שרברב" },
    { foreign: "אינסייט", hebrew: "תובנה" },
    { foreign: "אינפוזיה", hebrew: "עירוי" },
    { foreign: "אינפוט", hebrew: "קלט" },
    { foreign: "אינפורמציה", hebrew: "מידע" },
    { foreign: "אינפקציה", hebrew: "זיהום" },
    { foreign: "אינקובטור", hebrew: "חממית" },
    { foreign: "אינקוגניטו", hebrew: "בעילום שם" },
    { foreign: "אינקונבולה", hebrew: "דפוס ערש" },
    { foreign: "אינרציה", hebrew: "התמד" },
    { foreign: "אופוריה", hebrew: "זחיחות" },
    { foreign: "אכינצאה", hebrew: "קיפודנית" },
    { foreign: "אלטרואיזם", hebrew: "זולתנות" },
    { foreign: "אלטרואיסט", hebrew: "זולתני" },
    { foreign: "אלטרנטיבה", hebrew: "חלופה" },
    { foreign: "אלטרנטיבי", hebrew: "חלופי" },
    { foreign: "אליטה", hebrew: "עילית" },
    { foreign: "אליטיסטי", hebrew: "עיליתני" },
    { foreign: "אליפסיס", hebrew: "השמט" },
    { foreign: "אלרגי", hebrew: "רגשתי" },
    { foreign: "אלרגיה", hebrew: "רגשת" },
    { foreign: "אמבוש", hebrew: "מארב" },
    { foreign: "אמביציונר", hebrew: "שאפתן" },
    { foreign: "אמברגו", hebrew: "החסם" },
    { foreign: "אמולסיה", hebrew: "תחליב" },
    { foreign: "אמיגרנט", hebrew: "מהגר" },
    { foreign: "אמיגרציה", hebrew: "הגירה" },
    { foreign: "אמנזיה", hebrew: "שיכחון" },
    { foreign: "אמפולה", hebrew: "בקבוקית" },
    { foreign: "אמפירי", hebrew: "נסותי" },
    { foreign: "אנדוסקופ", hebrew: "משקף" },
    { foreign: "אנדרדוג", hebrew: "דל סיכוי" },
    { foreign: "אנדרוגיני", hebrew: "דו מיני" },
    { foreign: "אנונימי", hebrew: "עלום שם" },
    { foreign: "אנורקטי", hebrew: "ציימן" },
    { foreign: "אנורקסיה", hebrew: "ציימנות" },
    { foreign: "אנטיגן", hebrew: "אנגד" },
    { foreign: "אנטנה", hebrew: "משושה" },
    { foreign: "אניגמטי", hebrew: "חידתי" },
    { foreign: "אנימציה", hebrew: "הנפשה" },
    { foreign: "אנשובי", hebrew: "עפיין" },
    { foreign: "מאלט", hebrew: "לתת" },
    { foreign: "מאפין", hebrew: "מופין" },
    { foreign: "מארס", hebrew: "מאדים" },
    { foreign: "מגלומניה", hebrew: "שיגעון גדלות" },
    { foreign: "מדיטציה", hebrew: "בוננות" },
    { foreign: "מדליון", hebrew: "תליון" },
    { foreign: "מוביליות", hebrew: "ניידות" },
    { foreign: "מודה", hebrew: "אופנה" },
    { foreign: "מודולציה", hebrew: "אפנון" },
    { foreign: "מודוס אופרנדי", hebrew: "שיטת פעולה" },
    { foreign: "מודרני", hebrew: "חדיש" },
    { foreign: "מוזאיקה", hebrew: "פסיפס" },
    { foreign: "מוטור", hebrew: "מנוע" },
    { foreign: "מוטיבציה", hebrew: "הניעה" },
    { foreign: "מוטל", hebrew: "מלונית" },
    { foreign: "מוטציה", hebrew: "תשנית" },
    { foreign: "מולטידיסציפלינרי", hebrew: "רב־תחומי" },
    { foreign: "מולטיפוקל", hebrew: "רב־מוקדי" },
    { foreign: "מומיה", hebrew: "חנוט" },
    { foreign: "מונוטוני", hebrew: "חדגוני" },
    { foreign: "מונוטוניות", hebrew: "חדגוניות" },
    { foreign: "מונולוג", hebrew: "חד שיח" },
    { foreign: "מוניטור", hebrew: "צג" },
    { foreign: "מוניציפלי", hebrew: "עירוני" },
    { foreign: "מונרכיזם", hebrew: "מלוכנות" },
    { foreign: "מונרכייה", hebrew: "מלוכה" },
    { foreign: "מוס", hebrew: "קציפה" },
    { foreign: "טאב", hebrew: "לשונית" },
    { foreign: "טאבו", hebrew: "מרשם מקרקעין" },
    { foreign: "טאבלט", hebrew: "מחשב לוח" },
    { foreign: "טבולה רסה", hebrew: "לוח חלק" },
    { foreign: "טוטל לוס", hebrew: "אובדן גמור" },
    { foreign: "טוטליטרי", hebrew: "לופתני" },
    { foreign: "טוטליטריזם", hebrew: "לופתנות" },
    { foreign: "טולרנטיות", hebrew: "סובלנות" },
    { foreign: "טונוס", hebrew: "מתח שרירים" },
    { foreign: "טוניקה", hebrew: "ירכית" },
    { foreign: "טונר", hebrew: "מחסנית דיו" },
    { foreign: "טוסט", hebrew: "לחם קלוי" },
    { foreign: "טוסטר", hebrew: "מצנם" },
    { foreign: "טוסטר אובן", hebrew: "תנורון" },
    { foreign: "טוקבק", hebrew: "תגובית" },
    { foreign: "טוקבקיסט", hebrew: "תגובן" },
    { foreign: "טוקסין", hebrew: "רעלן" },
    { foreign: "טורבן", hebrew: "צניף" },
    { foreign: "טוש", hebrew: "מצבע" },
    { foreign: "טטנוס", hebrew: "צפדת" },
    { foreign: "טיימינג", hebrew: "תזמון" },
    { foreign: "טיימר", hebrew: "קוצב זמן" },
    { foreign: "טייפ", hebrew: "רשמקול" },
    { foreign: "טייץ", hebrew: "צמודונים" },
    { foreign: "טייק אוויי", hebrew: "קח ולך" },
    { foreign: "טייקון", hebrew: "איל הון" },
    { foreign: "טילדה", hebrew: "גל" },
    { foreign: "טיפ", hebrew: "תשר" },
    { foreign: "טיפקס", hebrew: "מחיקון" },
    { foreign: "טיק", hebrew: "פרכוס" },
    { foreign: "טישו", hebrew: "מלמלית" },
    { foreign: "טכנוקרטיה", hebrew: "שלטון מומחים" },
    { foreign: "טלגרמה", hebrew: "מברק" },
    { foreign: "טלר", hebrew: "כספר" },
    { foreign: "טמבון", hebrew: "פגוש" },
    { foreign: "טמפו", hebrew: "מפעם" },
    { foreign: "טמפרמנט", hebrew: "מזג" },
    { foreign: "טנדר", hebrew: "מטענית" },
    { foreign: "טקסטורה", hebrew: "מרקם" },
    { foreign: "טקסי", hebrew: "מונית" },
    { foreign: "טראומה", hebrew: "חובלה" },
    { foreign: "טראומטי", hebrew: "חובלני" },
    { foreign: "טרגוט", hebrew: "קיהול" },
    { foreign: "טריבונל", hebrew: "בית דין" },
    { foreign: "טריגר", hebrew: "מזנק" },
    { foreign: "טריטוריאלי", hebrew: "תחומתי" },
    { foreign: "טריטוריאליות", hebrew: "תחומתיות" },
    { foreign: "טריידר", hebrew: "סחרן" },
    { foreign: "טריילר", hebrew: "גרור" },
    { foreign: "טרמינולוגיה", hebrew: "מינוח" },
    { foreign: "טרמינל", hebrew: "מסוף" },
    { foreign: "טרמפולינה", hebrew: "קפצת" },
    { foreign: "טרנינג", hebrew: "אימונית" },
    { foreign: "טרנספורט", hebrew: "תובלה" },
    { foreign: "טרנספורטר", hebrew: "מוביל" },
    { foreign: "טרנספורמטור", hebrew: "שנאי" },
    { foreign: "טרנספורמציה", hebrew: "התמרה" },
    { foreign: "טרסה", hebrew: "מדרגה" },
    { foreign: "טשולנט", hebrew: "חמין" },
    { foreign: "פאוץ'", hebrew: "פונדה" },
    { foreign: "פאזל", hebrew: "תצרף" },
    { foreign: "פאי", hebrew: "תמליא" },
    { foreign: "פאנץ' ליין", hebrew: "שורת מחץ" },
    { foreign: "פארטי פופר", hebrew: "משבית שמחות" },
    { foreign: "פדל", hebrew: "דוושה" },
    { foreign: "פדנט", hebrew: "נוקדן" },
    { foreign: "פוביה", hebrew: "בעת" },
    { foreign: "פודיום", hebrew: "דוכן מנצחים" },
    { foreign: "פודינג", hebrew: "רפרפת" },
    { foreign: "פודפרוססור", hebrew: "מעבד מזון" },
    { foreign: "פודקאסט", hebrew: "הסכת" },
    { foreign: "פוזיטיבי", hebrew: "חיובי" },
    { foreign: "פוטוגרפיה", hebrew: "צילום" },
    { foreign: "פוטומונטז'", hebrew: "תמונה משובצת" },
    { foreign: "פוטוסינתזה", hebrew: "הטמעת אור" },
    { foreign: "פוטנציאל", hebrew: "יוכלה" },
    { foreign: "פוטש", hebrew: "הפיכה" },
    { foreign: "פוינטר", hebrew: "מצביע" },
    { foreign: "פוליגון", hebrew: "מצולע" },
    { foreign: "פוליגרף", hebrew: "גלאי שקר" },
    { foreign: "פוליו", hebrew: "שיתוק ילדים" },
    { foreign: "פוליטיקלי קורקט", hebrew: "תקין פוליטית" },
    { foreign: "פוליסמי", hebrew: "רב משמעי" },
    { foreign: "פוליפוני", hebrew: "רב קולי" },
    { foreign: "פוליפוניה", hebrew: "רב קוליות" },
    { foreign: "פולס", hebrew: "דופק" },
    { foreign: "פולרי", hebrew: "קוטבי" },
    { foreign: "פולריזציה", hebrew: "קיטוב" },
    { foreign: "פומפה", hebrew: "פמפמת" },
    { foreign: "פומפון", hebrew: "פיף" },
    { foreign: "פונדמנטלי", hebrew: "יסודני" },
    { foreign: "פונדמנטליזם", hebrew: "יסודנות" },
    { foreign: "פונט", hebrew: "גופן" },
    { foreign: "פונמה", hebrew: "הגיין" },
    { foreign: "פונקציונלי", hebrew: "תפקודי" },
    { foreign: "פונקציונליזם", hebrew: "תפקודנות" },
    { foreign: "פוסט", hebrew: "רשומה" },
    { foreign: "פוסטה", hebrew: "דואר" },
    { foreign: "פוסטר", hebrew: "כרזה" },
    { foreign: "פוספור", hebrew: "זרחן" },
    { foreign: "פופ אפ", hebrew: "חלון צץ" },
    { foreign: "פופוליזם", hebrew: "המונאות" },
    { foreign: "פופקורן", hebrew: "פצפוצי תירס" },
    { foreign: "פורטפוליו", hebrew: "תיק עבודות" },
    { foreign: "פורטרט", hebrew: "דיוקן" },
    { foreign: "פוריזם", hebrew: "טהרנות" },
    { foreign: "פוריסט", hebrew: "טהרן" },
    { foreign: "פורל", hebrew: "טרוטה" },
    { foreign: "פורמלי", hebrew: "רשמי" },
    { foreign: "פורניר", hebrew: "קליף" },
    { foreign: "פורס מז'ור", hebrew: "כוח עליון" },
    { foreign: "פורצלן", hebrew: "חרסינה" },
    { foreign: "פטיציה", hebrew: "עצומה" },
    { foreign: "פטלי", hebrew: "גורלי" },
    { foreign: "פטפון", hebrew: "מקול" },
    { foreign: "פטריארכלי", hebrew: "אבהתני" },
    { foreign: "פטריארכליות", hebrew: "אבהתנות" },
    { foreign: "פטריוט", hebrew: "מולדתן" },
    { foreign: "פטריוטיזם", hebrew: "מולדתנות" },
    { foreign: "פיג'מה", hebrew: "חליפת שינה" },
    { foreign: "פיגמנט", hebrew: "צבען" },
    { foreign: "פידבק", hebrew: "משוב" },
    { foreign: "פיוז", hebrew: "נתיך" },
    { foreign: "פייסר", hebrew: "מכתיב קצב" },
    { foreign: "פייפ", hebrew: "מקטרת" },
    { foreign: "פייק ניוז", hebrew: "חדשות כזב" },
    { foreign: "פיירוול", hebrew: "חומת אש" },
    { foreign: "פילבוקס", hebrew: "מצדית" },
    { foreign: "פילטר", hebrew: "מסנן" },
    { foreign: "פיליבסטר", hebrew: "נאום התשה" },
    { foreign: "פיקצייה", hebrew: "מבדה" },
    { foreign: "פיקשן", hebrew: "בדיון" },
    { foreign: "פיראט", hebrew: "שודד ים" },
    { foreign: "פירה", hebrew: "מחית" },
    { foreign: "פירומן", hebrew: "מציתן" },
    { foreign: "פירסינג", hebrew: "ניזום" },
    { foreign: "פלאג", hebrew: "מצת" },
    { foreign: "פלינדרום", hebrew: "מילה מתהפכת" },
    { foreign: "פליקן", hebrew: "שקנאי" },
    { foreign: "פלירט", hebrew: "אהבהבים" },
    { foreign: "פלנטה", hebrew: "כוכב לכת" },
    { foreign: "פלסטלינה", hebrew: "טינית" },
    { foreign: "פלסטר", hebrew: "אספלנית" },
    { foreign: "פלצבו", hebrew: "תרופת דמה" },
    { foreign: "פנדל", hebrew: "בעיטת עונשין" },
    { foreign: "פנומן", hebrew: "תופעה" },
    { foreign: "פנטגון", hebrew: "מחומש" },
    { foreign: "פנטהאוס", hebrew: "דירת גג" },
    { foreign: "פניקה", hebrew: "תבהלה" },
    { foreign: "פנסיון", hebrew: "בית הבראה" },
    { foreign: "פנסיונר", hebrew: "גמלאי" },
    { foreign: "פנצ'ר", hebrew: "נקר" },
    { foreign: "פנצ'ר מאכער", hebrew: "צמיגאי" },
    { foreign: "פנצ'רייה", hebrew: "צמיגייה" },
    { foreign: "פנקייק", hebrew: "חמיטה" },
    { foreign: "פסוריאזיס", hebrew: "ספחת" },
    { foreign: "פסז'", hebrew: "מפלש" },
    { foreign: "פסטורליזם", hebrew: "רועיות" },
    { foreign: "פסיבי", hebrew: "סביל" },
    { foreign: "פסיביות", hebrew: "סבילות" },
    { foreign: "פסיפלורה", hebrew: "שעונית" },
    { foreign: "פספורט", hebrew: "דרכון" },
    { foreign: "פפריקה", hebrew: "פלפלת" },
    { foreign: "פצפיזם", hebrew: "שלומנות" },
    { foreign: "פראק", hebrew: "מכנף" },
    { foreign: "פרגולה", hebrew: "מצללה" },
    { foreign: "פרודוקט", hebrew: "מצרך" },
    { foreign: "פרווה", hebrew: "סתמי" },
    { foreign: "פרוורטי", hebrew: "סוטה" },
    { foreign: "פרוז'קטור", hebrew: "זרקור" },
    { foreign: "פרוטאין", hebrew: "חלבון" },
    { foreign: "פרוטוטיפ", hebrew: "אב טיפוס" },
    { foreign: "פרוטוקול", hebrew: "זיכרון דברים" },
    { foreign: "פרויקט", hebrew: "מיזם" },
    { foreign: "פרויקטור", hebrew: "מנהל מיזם" },
    { foreign: "פרוסטטה", hebrew: "ערמונית" },
    { foreign: "פרוססור", hebrew: "מעבד" },
    { foreign: "פרוספקט", hebrew: "עלון מידע" },
    { foreign: "פרופגנדה", hebrew: "תעמולה" },
    { foreign: "פרופלור", hebrew: "מדחף" },
    { foreign: "פרוצס", hebrew: "תהליך" },
    { foreign: "פרותזה", hebrew: "תותבת" },
    { foreign: "פרזיט", hebrew: "טפיל" },
    { foreign: "פרזנטור", hebrew: "יצגן" },
    { foreign: "פרטיטורה", hebrew: "תכליל" },
    { foreign: "פריג'ידר", hebrew: "מקרר" },
    { foreign: "פריזמה", hebrew: "מנסרה" },
    { foreign: "פריזר", hebrew: "מקפיא" },
    { foreign: "פריטטי", hebrew: "שקול" },
    { foreign: "פריטטיות", hebrew: "שקילות" },
    { foreign: "פריים טיים", hebrew: "שעת שיא" },
    { foreign: "פריימריז", hebrew: "בחירות מקדימות" },
    { foreign: "פרימטר", hebrew: "היקף" },
    { foreign: "פריפריאלי", hebrew: "היקפי" },
    { foreign: "פרלוד", hebrew: "אקדמה" },
    { foreign: "פרלין", hebrew: "מוליה" },
    { foreign: "פרמיירה", hebrew: "הצגת בכורה" },
    { foreign: "פרסוניפיקציה", hebrew: "האנשה" },
    { foreign: "פרסונלי", hebrew: "אישי" },
    { foreign: "פרסטיז'ה", hebrew: "יוקרה" },
    { foreign: "פרספקטיבה", hebrew: "תשקופת" },
    { foreign: "פרסקו", hebrew: "תמשיח" },
    { foreign: "פרעצל", hebrew: "שלובית" },
    { foreign: "פרפום", hebrew: "בושם" },
    { foreign: "פרפומריה", hebrew: "תמרוקייה" },
    { foreign: "פרפורמנס", hebrew: "מיצג" },
    { foreign: "פרפקט", hebrew: "מושלם" },
    { foreign: "פתוגן", hebrew: "מרען" },
    { foreign: "שאטל", hebrew: "היסעית" },
    { foreign: "שאסי", hebrew: "שלדה" },
    { foreign: "שוק", hebrew: "הלם" },
    { foreign: "שוקולטייר", hebrew: "שוקולדאי" },
    { foreign: "שוקר חשמלי", hebrew: "מהלום" },
    { foreign: "שטנץ", hebrew: "דפוס" },
    { foreign: "שטקר", hebrew: "תקע" },
    { foreign: "שטרודל", hebrew: "כרוכית" },
    { foreign: "שייבה", hebrew: "דסקית" },
    { foreign: "שיימינג", hebrew: "ביוש" },
    { foreign: "שייק", hebrew: "קציף" },
    { foreign: "ראורגניזציה", hebrew: "ארגון מחדש" },
    { foreign: "ראנר", hebrew: "שבילה" },
    { foreign: "רבולוציה", hebrew: "מהפכה" },
    { foreign: "רדאר", hebrew: "מכם" },
    { foreign: "רדיוס", hebrew: "חישור" },
    { foreign: "רדיקליזם", hebrew: "קיצוניות" },
    { foreign: "רוורס", hebrew: "הילוך אחורי" },
    { foreign: "רוטינה", hebrew: "שגרה" },
    { foreign: "רוטיני", hebrew: "שגרתי" },
    { foreign: "רוטציה", hebrew: "סבב" },
    { foreign: "רזומה", hebrew: "קורות חיים" },
    { foreign: "רזרבה", hebrew: "עתודה" },
    { foreign: "רטרוספקטיבי", hebrew: "אחורני" },
    { foreign: "ריאליה", hebrew: "מציאות" },
    { foreign: "ריאליזם", hebrew: "מציאותנות" },
    { foreign: "ריאליסט", hebrew: "מציאותני" },
    { foreign: "ריאקצייה", hebrew: "תגובה" },
    { foreign: "ריבאונד", hebrew: "כדור ניתר" },
    { foreign: "רייטינג", hebrew: "מדרוג" },
    { foreign: "ריל טיים", hebrew: "זמן אמת" },
    { foreign: "רילוקיישן", hebrew: "עיתוק" },
    { foreign: "רינגטון", hebrew: "נעימון" },
    { foreign: "ריף", hebrew: "שונית" },
    { foreign: "ריצ'רץ'", hebrew: "רוכסן" },
    { foreign: "ריתמוס", hebrew: "מקצב" },
    { foreign: "רכב היברידי", hebrew: "רכב כלאיים" },
    { foreign: "רלטיבי", hebrew: "יחסי" },
    { foreign: "רליגיוזי", hebrew: "דתי" },
    { foreign: "רליגיוזיות", hebrew: "דתיות" },
    { foreign: "רמפה", hebrew: "כבש" },
    { foreign: "רנדומלי", hebrew: "אקראי" },
    { foreign: "רסטורציה", hebrew: "שחזור" },
    { foreign: "רסיבר", hebrew: "מקלט" },
    { foreign: "רספקט", hebrew: "כבוד" },
    { foreign: "רפטיטיבי", hebrew: "חזרתי" },
    { foreign: "רפרזנטטיבי", hebrew: "ייצוגי" },
    { foreign: "רציונלי", hebrew: "שכלתני" },
    { foreign: "רציונליות", hebrew: "שכלתנות" },
    { foreign: "רציונליסט", hebrew: "שכלתן" },
    { foreign: "רצסיבי", hebrew: "נסגני" },
    { foreign: "רצפט", hebrew: "מרשם" },
    { foreign: "רקורד", hebrew: "שיא" },
    { foreign: "רקורסיבי", hebrew: "נסוג" },
    { foreign: "רקלמה", hebrew: "פרסומת" },
    { foreign: "של", hebrew: "רדיד" },
    { foreign: "שלאגר", hebrew: "להיט" },
    { foreign: "שלוקר", hebrew: "חמת" },
    { foreign: "שלטר", hebrew: "מפסק" },
    { foreign: "שלייקס", hebrew: "כתפות" },
    { foreign: "שמפו", hebrew: "תחפיף" },
    { foreign: "שנורקל", hebrew: "צנרן" },
    { foreign: "שניצל", hebrew: "כתיתה" },
    { foreign: "שף", hebrew: "אשף" },
    { foreign: "שפיץ", hebrew: "חוד" },
    { foreign: "שפכטל", hebrew: "מרית" },
    { foreign: "שרימפ", hebrew: "חסילון" },
    { foreign: "לאנג'", hebrew: "מכרע" },
    { foreign: "לבורנט", hebrew: "מעבדן" },
    { foreign: "לבירינת", hebrew: "מבוך" },
    { foreign: "לגלי", hebrew: "חוקי" },
    { foreign: "לגנדה", hebrew: "אגדה" },
    { foreign: "לואו קוסט", hebrew: "טיסת חסך" },
    { foreign: "לוביסט", hebrew: "שדלן" },
    { foreign: "לוגו", hebrew: "סמליל" },
    { foreign: "לוגי", hebrew: "הגיוני" },
    { foreign: "לוונדר", hebrew: "אזוביון" },
    { foreign: "לויאלי", hebrew: "נאמן" },
    { foreign: "לויאליות", hebrew: "נאמנות" },
    { foreign: "לוף", hebrew: "קציץ" },
    { foreign: "לוקלי", hebrew: "מקומי" },
    { foreign: "לוקסוס", hebrew: "מותרות" },
    { foreign: "לטקס", hebrew: "לביבות" },
    { foreign: "ליברטריאניזם", hebrew: "חירותנות" },
    { foreign: "ליברליזם", hebrew: "חירותיות" },
    { foreign: "ליטרלי", hebrew: "מילולי" },
    { foreign: "ליין־אפ", hebrew: "תסדיר" },
    { foreign: "לייסט", hebrew: "פסיס" },
    { foreign: "לימינלי", hebrew: "סיפי" },
    { foreign: "לימינליות", hebrew: "סיפיות" },
    { foreign: "לינגוויסטיקה", hebrew: "בלשנות" },
    { foreign: "לינולאום", hebrew: "שעמנית" },
    { foreign: "לקסיקולוגיה", hebrew: "מילונות" },
    { foreign: "לקסיקלי", hebrew: "מילוני" },
    { foreign: "דאבל", hebrew: "כפול" },
    { foreign: "דאודורנט", hebrew: "אל ריח" },
    { foreign: "דאטה", hebrew: "נתונים" },
    { foreign: "דאטה בייס", hebrew: "מסד נתונים" },
    { foreign: "דה יורה", hebrew: "להלכה" },
    { foreign: "דה־לגיטימציה", hebrew: "הפסלה" },
    { foreign: "דה־פקטו", hebrew: "למעשה" },
    { foreign: "דואט", hebrew: "דואית" },
    { foreign: "דואליות", hebrew: "שניות" },
    { foreign: "דולה", hebrew: "תומכת לידה" },
    { foreign: "דולי", hebrew: "צלמנוע" },
    { foreign: "דולינה", hebrew: "בולען" },
    { foreign: "דומיין", hebrew: "תחום" },
    { foreign: "דונגל", hebrew: "תקיע" },
    { foreign: "דופליקציה", hebrew: "הכפלה" },
    { foreign: "דוקומנט", hebrew: "מסמך" },
    { foreign: "דוקומנטרי", hebrew: "תיעודי" },
    { foreign: "דוקטרינה", hebrew: "משנה" },
    { foreign: "דוש", hebrew: "מקלח" },
    { foreign: "דטרגנט", hebrew: "בוריתן" },
    { foreign: "דטרמיניזם", hebrew: "כורחנות" },
    { foreign: "דטרמיניסטי", hebrew: "כורחני" },
    { foreign: "די־ג'יי", hebrew: "תקליטן" },
    { foreign: "דיאז", hebrew: "נסק" },
    { foreign: "דיאטן", hebrew: "תזונאי" },
    { foreign: "דיאלוג", hebrew: "דו שיח" },
    { foreign: "דיאלקט", hebrew: "להג" },
    { foreign: "דיאספורה", hebrew: "פזורה" },
    { foreign: "דיאפזון", hebrew: "מנעד" },
    { foreign: "דיבייט", hebrew: "מעמת" },
    { foreign: "דיבל", hebrew: "מיתד" },
    { foreign: "דיגיטלי", hebrew: "ספרתי" },
    { foreign: "דיוויזיה", hebrew: "אוגדה" },
    { foreign: "דיונה", hebrew: "חולית" },
    { foreign: "דיז'סטיף", hebrew: "אפטר" },
    { foreign: "דיזיינר", hebrew: "מעצב" },
    { foreign: "דיזרט", hebrew: "פרפרת" },
    { foreign: "דיל", hebrew: "עסקה" },
    { foreign: "דילטנט", hebrew: "חובבן" },
    { foreign: "דילטנטיות", hebrew: "חובבנות" },
    { foreign: "דימר", hebrew: "עמעם" },
    { foreign: "דיסוננס", hebrew: "צרימה" },
    { foreign: "דיסטריביוטור", hebrew: "מפלג" },
    { foreign: "דיסידנט", hebrew: "פליג" },
    { foreign: "דיסימילציה", hebrew: "היבדלות" },
    { foreign: "דיסק און קי", hebrew: "החסן נייד" },
    { foreign: "דיסקורס", hebrew: "שיח" },
    { foreign: "דיסקט", hebrew: "תקליטון" },
    { foreign: "דיפ־סטייט", hebrew: "מדינת צללים" },
    { foreign: "דיפו", hebrew: "קרפיף" },
    { foreign: "דיפוזיה", hebrew: "פעפוע" },
    { foreign: "דיפולט", hebrew: "ברירת מחדל" },
    { foreign: "דיפרנציאציה", hebrew: "בידול" },
    { foreign: "דמגוגיה", hebrew: "מלהיגות" },
    { foreign: "דמונסטרציה", hebrew: "הפגנה" },
    { foreign: "דמנטי", hebrew: "קהיוני" },
    { foreign: "דמנסייה", hebrew: "קיהיון" },
    { foreign: "דנטין", hebrew: "שנהב" },
    { foreign: "דסק", hebrew: "מדור" },
    { foreign: "דפיברילטור", hebrew: "מפעם" },
    { foreign: "דפיציט", hebrew: "גירעון" },
    { foreign: "דפנסיבה", hebrew: "מגננה" },
    { foreign: "דפנסיבי", hebrew: "מתגונן" },
    { foreign: "דק", hebrew: "ספן" },
    { foreign: "דקונסטרוקצייה", hebrew: "פירוק" },
    { foreign: "דקורטיבי", hebrew: "קישוטי" },
    { foreign: "דקלרטיבי", hebrew: "הצהרתי" },
    { foreign: "דקלרציה", hebrew: "הצהרה" }
];
