export const wordList = [
    { foreign: "אנתרקס", hebrew: "גחלת" },
    { foreign: "אס-אם-אס", hebrew: "מסרון" },
    { foreign: "אסיסטנט", hebrew: "סייע" },
    { foreign: "אספירציה", hebrew: "שאיפה" },
    { foreign: "אספקט", hebrew: "הבט" },
    { foreign: "אסקלציה", hebrew: "הסלמה" },
    { foreign: "אסקפיזם", hebrew: "בורחנות" },
    { foreign: "אסתמה", hebrew: "קצרת" },
    { foreign: "אפטר", hebrew: "חופשון" },
    { foreign: "אפידמיה", hebrew: "מגפה" },
    { foreign: "אפיליפסיה", hebrew: "כפיון" },
    { foreign: "אפליקציה", hebrew: "יישומון" },
    { foreign: "אפנדיציט", hebrew: "תוספתן" },
    { foreign: "אפריטיף", hebrew: "אקדם" },
    { foreign: "אפתיה", hebrew: "אידשון" },
    { foreign: "אקוודוקט", hebrew: "אמת מים" },
    { foreign: "אקוויפר", hebrew: "אקווה" },
    { foreign: "אקווילייזר", hebrew: "שוויין" },
    { foreign: "אקונומי", hebrew: "כלכלי" },
    { foreign: "אקורד", hebrew: "תצליל" },
    { foreign: "אקורדיון", hebrew: "מפוחון" },
    { foreign: "אקזיט", hebrew: "הנפק" },
    { foreign: "אקזיסטציאלי", hebrew: "קיומי" },
    { foreign: "אקזמה", hebrew: "גרב" },
    { foreign: "אקטיבי", hebrew: "פעיל" },
    { foreign: "אקטיביזם", hebrew: "פעילנות" },
    { foreign: "אקנה", hebrew: "חטטת" },
    { foreign: "אקספוננציאלי", hebrew: "מעריכי" },
    { foreign: "אקספורט", hebrew: "יצוא" },
    { foreign: "אקצנט", hebrew: "מבטא" },
    { foreign: "אקרובט", hebrew: "לוליין" },
    { foreign: "אירובי", hebrew: "אווירני" },
    { foreign: "ארומה", hebrew: "בשומת" },
    { foreign: "ארטישוק", hebrew: "קנרס" },
    { foreign: "אתי", hebrew: "מוסרי" },
    { foreign: "באג", hebrew: "תקל" },
    { foreign: "באולינג", hebrew: "כדורת" },
    { foreign: "באז", hebrew: "רחשת" },
    { foreign: "באגאז'", hebrew: "תא מטען" },
    { foreign: "בדמינטון", hebrew: "נוצית" },
    { foreign: "בוטקה", hebrew: "שומרה" },
    { foreign: "בולדוזר", hebrew: "דחפור" },
    { foreign: "בולימיה", hebrew: "זללת" },
    { foreign: "בונקר", hebrew: "מבצור" },
    { foreign: "בופה", hebrew: "מזנון" },
    { foreign: "בורגול", hebrew: "ריפות" },
    { foreign: "בורי", hebrew: "קיפון" },
    { foreign: "בורשט", hebrew: "חמיצה" },
    { foreign: "בזיליקום", hebrew: "ריחן" },
    { foreign: "בטרייה", hebrew: "סוללה" },
    { foreign: "ביהביוריזם", hebrew: "התנהגותנות" },
    { foreign: "ביזנס", hebrew: "עסק" },
    { foreign: "בייבי גרו", hebrew: "מגמשת" },
    { foreign: "בייביסיטר", hebrew: "שמרטף" },
    { foreign: "בייגל", hebrew: "כעך" },
    { foreign: "בייסבול", hebrew: "כדור בסיס" },
    { foreign: "בילט אין", hebrew: "מובנה" },
    { foreign: "בילטרלי", hebrew: "דו צדדי" },
    { foreign: "ביס", hebrew: "נגיסה" },
    { foreign: "ביסקויט", hebrew: "מרקוע" },
    { foreign: "רולדה", hebrew: "גלילה" },
    { foreign: "סטייק", hebrew: "אומצה" },
    { foreign: "צ'יפס", hebrew: "טוגנים" },
    { foreign: "אאוטלט", hebrew: "חנות עודפים" },
    { foreign: "אאוטסורסינג", hebrew: "מיקור חוץ" },
    { foreign: "אאוטפוט", hebrew: "פלט" },
    { foreign: "אבסולוטי", hebrew: "מוחלט" },
    { foreign: "אבסטרקט", hebrew: "תקציר" },
    { foreign: "אבסטרקטי", hebrew: "מופשט" },
    { foreign: "אג'נדה", hebrew: "סדר יום" },
    { foreign: "אגואיזם", hebrew: "אנוכיות" },
    { foreign: "אגואיסט", hebrew: "אנוכי" },
    { foreign: "אגזוז", hebrew: "צינור פליטה" },
    { foreign: "אגרסיבי", hebrew: "תוקפני" },
    { foreign: "אדמינסטרטיבי", hebrew: "מנהלי" },
    { foreign: "אדפטציה", hebrew: "הסתגלות" },
    { foreign: "אובלי", hebrew: "סגלגל" },
    { foreign: "אובססיבי", hebrew: "טירדוני" },
    { foreign: "אובססיה", hebrew: "טירדון" },
    { foreign: "אוברדרפט", hebrew: "משיכת יתר" },
    { foreign: "אודיו", hebrew: "שמע" },
    { foreign: "אודישן", hebrew: "מבחן במה" },
    { foreign: "אווטר", hebrew: "יצגן" },
    { foreign: "אוטונומיה", hebrew: "ממשל עצמי" },
    { foreign: "אוטוסטרדה", hebrew: "דרך מהירה" },
    { foreign: "אולטרה סגול", hebrew: "על סגול" },
    { foreign: "אוליגרכיה", hebrew: "שלטון קומץ" },
    { foreign: "אומלט", hebrew: "חביתה" },
    { foreign: "אונומטופאה", hebrew: "תצליל" },
    { foreign: "אונליין", hebrew: "מקוון" },
    { foreign: "אוסמוזה", hebrew: "פעפוע" },
    { foreign: "אופוזיציה", hebrew: "נגדה" },
    { foreign: "אופורטוניזם", hebrew: "הזדמננות" },
    { foreign: "אופטימום", hebrew: "מיטב" },
    { foreign: "אופטימיזציה", hebrew: "מיטוב" },
    { foreign: "אופטימלי", hebrew: "מיטבי" },
    { foreign: "אופנסיבה", hebrew: "מתקפה" },
    { foreign: "אופסייד", hebrew: "נבדל" },
    { foreign: "אוקטגון", hebrew: "מתומן" },
    { foreign: "אוקסימורון", hebrew: "ניב ניגודים" },
    { foreign: "אורבני", hebrew: "עירוני" },
    { foreign: "אורגנו", hebrew: "אזובית" },
    { foreign: "אורגניזם", hebrew: "יצור" },
    { foreign: "אטימולוגיה", hebrew: "גיזרון" },
    { foreign: "אטצ'מנט", hebrew: "צרופה" },
    { foreign: "אטרקטיבי", hebrew: "מושך" },
    { foreign: "אידיום", hebrew: "ניב" },
    { foreign: "איי קיו", hebrew: "מנת משכל" },
    { foreign: "אייטם", hebrew: "פריט" },
    { foreign: "אילוזיה", hebrew: "אשליה" },
    { foreign: "אימג'", hebrew: "תמונה" },
    { foreign: "אימוג'י", hebrew: "סמלון" },
    { foreign: "אימיגרציה", hebrew: "הגירה" },
    { foreign: "אימייל", hebrew: "דואר אלקטרוני" },
    { foreign: "אימפולסיבי", hebrew: "פרצני" },
    { foreign: "אימפורט", hebrew: "יבוא" },
    { foreign: "אימפטיגו", hebrew: "גלדת" },
    { foreign: "אימפרוביזציה", hebrew: "אלתור" },
    { foreign: "אינג'יניר", hebrew: "מהנדס" },
    { foreign: "אינדיפרנטי", hebrew: "אדיש" },
    { foreign: "אינדקס", hebrew: "מדד" },
    { foreign: "אינטגריטי", hebrew: "יושרה" },
    { foreign: "אינטונציה", hebrew: "הנגנה" },
    { foreign: "אינטנסיבי", hebrew: "עצים" },
    { foreign: "אינטראקטיבי", hebrew: "הידודי" },
    { foreign: "אינטרדיסציפליני", hebrew: "בין תחומי" },
    { foreign: "אינטרנט", hebrew: "מרשתת" },
    { foreign: "אינטרנציונלי", hebrew: "בין לאומי" },
    { foreign: "אינסטלטור", hebrew: "שרברב" },
    { foreign: "אינסייט", hebrew: "תובנה" },
    { foreign: "אינפוזיה", hebrew: "עירוי" },
    { foreign: "אינפוט", hebrew: "קלט" },
    { foreign: "אינפורמציה", hebrew: "מידע" },
    { foreign: "אינפקציה", hebrew: "זיהום" },
    { foreign: "אינקובטור", hebrew: "חממית" },
    { foreign: "אינקוגניטו", hebrew: "בעילום שם" },
    { foreign: "אינקונבולה", hebrew: "דפוס ערש" },
    { foreign: "אינרציה", hebrew: "התמד" },
    { foreign: "אופוריה", hebrew: "זחיחות" },
    { foreign: "אכינצאה", hebrew: "קיפודנית" },
    { foreign: "אלטרואיזם", hebrew: "זולתנות" },
    { foreign: "אלטרואיסט", hebrew: "זולתני" },
    { foreign: "אלטרנטיבה", hebrew: "חלופה" },
    { foreign: "אלטרנטיבי", hebrew: "חלופי" },
    { foreign: "אליטה", hebrew: "עילית" },
    { foreign: "אליטיסטי", hebrew: "עיליתני" },
    { foreign: "אליפסיס", hebrew: "השמט" },
    { foreign: "אלרגי", hebrew: "רגשתי" },
    { foreign: "אלרגיה", hebrew: "רגשת" },
    { foreign: "אמבוש", hebrew: "מארב" },
    { foreign: "אמביציונר", hebrew: "שאפתן" },
    { foreign: "אמברגו", hebrew: "החסם" },
    { foreign: "אמולסיה", hebrew: "תחליב" },
    { foreign: "אמיגרנט", hebrew: "מהגר" },
    { foreign: "אמיגרציה", hebrew: "הגירה" },
    { foreign: "אמנזיה", hebrew: "שיכחון" },
    { foreign: "אמפולה", hebrew: "בקבוקית" },
    { foreign: "אמפירי", hebrew: "נסותי" },
    { foreign: "אנדוסקופ", hebrew: "משקף" },
    { foreign: "אנדרדוג", hebrew: "דל סיכוי" },
    { foreign: "אנדרוגיני", hebrew: "דו מיני" },
    { foreign: "אנונימי", hebrew: "עלום שם" },
    { foreign: "אנורקטי", hebrew: "ציימן" },
    { foreign: "אנורקסיה", hebrew: "ציימנות" },
    { foreign: "אנטיגן", hebrew: "אנגד" },
    { foreign: "אנטנה", hebrew: "משושה" },
    { foreign: "אניגמטי", hebrew: "חידתי" },
    { foreign: "אנימציה", hebrew: "הנפשה" },
    { foreign: "אנשובי", hebrew: "עפיין" }
];
