const wordList = [
    { foreign: "אנתרקס", hebrew: "גחלת" },
    { foreign: "אס-אם-אס", hebrew: "מסרון" },
    { foreign: "אסיסטנט", hebrew: "סייע" },
    { foreign: "אספירציה", hebrew: "שאיפה" },
    { foreign: "אספקט", hebrew: "הבט" },
    { foreign: "אסקלציה", hebrew: "הסלמה" },
    { foreign: "אסקפיזם", hebrew: "בורחנות" },
    { foreign: "אסתמה", hebrew: "קצרת" },
    { foreign: "אפטר", hebrew: "חופשון" },
    { foreign: "אפידמיה", hebrew: "מגפה" },
    { foreign: "אפיליפסיה", hebrew: "כפיון" },
    { foreign: "אפליקציה", hebrew: "יישומון" },
    { foreign: "אפנדיציט", hebrew: "תוספתן" },
    { foreign: "אפריטיף", hebrew: "אקדם" },
    { foreign: "אפתיה", hebrew: "אידשון" },
    { foreign: "אקוודוקט", hebrew: "אמת מים" },
    { foreign: "אקוויפר", hebrew: "אקוה" },
    { foreign: "אקווילייזר", hebrew: "שוויין" },
    { foreign: "אקונומי", hebrew: "כלכלי" },
    { foreign: "אקורד", hebrew: "תצליל" },
    { foreign: "אקורדיון", hebrew: "מפוחון" },
    { foreign: "אקזיט", hebrew: "הנפק" },
    { foreign: "אקזיסטציאלי", hebrew: "קיומי" },
    { foreign: "אקזמה", hebrew: "גרב" },
    { foreign: "אקטיבי", hebrew: "פעיל" },
    { foreign: "אקטיביזם", hebrew: "פעילנות" },
    { foreign: "אקנה", hebrew: "חטטת" },
    { foreign: "אקספוננציאלי", hebrew: "מעריכי" },
    { foreign: "אקספורט", hebrew: "יצוא" },
    { foreign: "אקצנט", hebrew: "מבטא" },
    { foreign: "אקרובט", hebrew: "לוליין" },
    { foreign: "אירובי", hebrew: "אווירני" },
    { foreign: "ארומה", hebrew: "בשומת" },
    { foreign: "ארטישוק", hebrew: "קנרס" },
    { foreign: "אתי", hebrew: "מוסרי" },
    { foreign: "באג", hebrew: "תקל" },
    { foreign: "באולינג", hebrew: "כדורת" },
    { foreign: "באז", hebrew: "רחשת" },
    { foreign: "באגאז'", hebrew: "תא מטען" },
    { foreign: "בדמינטון", hebrew: "נוצית" },
    { foreign: "בוטקה", hebrew: "שומרה" },
    { foreign: "בולדוזר", hebrew: "דחפור" },
    { foreign: "בולימיה", hebrew: "זללת" },
    { foreign: "בונקר", hebrew: "מבצור" },
    { foreign: "בופה", hebrew: "מזנון" },
    { foreign: "בורגול", hebrew: "ריפות" },
    { foreign: "בורי", hebrew: "קיפון" },
    { foreign: "בורשט", hebrew: "חמיצה" },
    { foreign: "בזיליקום", hebrew: "ריחן" },
    { foreign: "בטרייה", hebrew: "סוללה" },
    { foreign: "ביהביוריזם", hebrew: "התנהגותנות" },
    { foreign: "ביזנס", hebrew: "עסק" },
    { foreign: "בייבי גרו", hebrew: "מגמשת" },
    { foreign: "בייביסיטר", hebrew: "שמרטף" },
    { foreign: "בייגל", hebrew: "כעך" },
    { foreign: "בייסבול", hebrew: "כדור בסיס" },
    { foreign: "בילט אין", hebrew: "מובנה" },
    { foreign: "בילטרלי", hebrew: "דו צדדי" },
    { foreign: "ביס", hebrew: "נגיסה" },
    { foreign: "ביסקויט", hebrew: "מרקוע" }
];
